### ISSUE TITLE
contact page

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#10]
@geekwise-veronica-chavez please adjust the font types in the contact box to match

![screen shot 2016-05-24 at 8 55 37 am](https://cloud.githubusercontent.com/assets/7436666/15510678/50347d94-218d-11e6-81b4-82c7c0ef09fe.png)

**Comment by geekwise-veronica-chavez** [comment]
font-family ciria ...  for email.. done
