### ISSUE TITLE
sign up page

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#11]
@geekwise-veronica-chavez please style the font types accordingly

![screen shot 2016-05-24 at 8 56 11 am](https://cloud.githubusercontent.com/assets/7436666/15510772/b7ea484c-218d-11e6-87ec-934caa8bf2d1.png)

**Comment by geekwise-veronica-chavez** [comment]
@Sramos9191 06/9/2016

**Comment by geekwise-veronica-chavez** [comment]
this is done
