### ISSUE TITLE
responsive - home page - bottom half

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#12]
the icons at the bottom push too far to the right

their bottom half:
![their-home-bottom-half](https://cloud.githubusercontent.com/assets/7436666/15559686/3fa9efd8-2299-11e6-90e3-9e1577bf0f93.png)

your bottom half:
![your-home-bottom-half](https://cloud.githubusercontent.com/assets/7436666/15559687/3faa1742-2299-11e6-8571-4bb4f5d73892.png)

**Comment by geekwise-veronica-chavez** [comment]
done
