### ISSUE TITLE
responsive - home page - menu

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#13]
you're missing the hamburger icon and sign up page highlighted in yellow

their menu:
![their-menu](https://cloud.githubusercontent.com/assets/7436666/15559706/7839747c-2299-11e6-96b9-34baf63a23d9.png)

your menu:
![your-menu](https://cloud.githubusercontent.com/assets/7436666/15559707/784f41da-2299-11e6-98e0-adfe70315890.png)

**Comment by geekwise-veronica-chavez** [comment]
bootstrap link in place was missing
