### ISSUE TITLE
responsive - about - background color

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#14]
background needs to be red so that the white text will show up 

theirs:
![their-about-page](https://cloud.githubusercontent.com/assets/7436666/15559756/d25314d6-2299-11e6-9265-bee304147899.png)

yours:
![your-about-page](https://cloud.githubusercontent.com/assets/7436666/15559755/d25280fc-2299-11e6-92c0-c99591e4457d.png)

**Comment by geekwise-veronica-chavez** [comment]
fixed the height issue and media query
