### ISSUE TITLE
responsive - courses - paragraph

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#16]
they should span the width of the browser (100%) 

![their-top-paragraph-course-page](https://cloud.githubusercontent.com/assets/7436666/15559878/c80611b2-229a-11e6-9a36-8bc37e2c532f.png)

![your-top-paragraph](https://cloud.githubusercontent.com/assets/7436666/15559877/c80420a0-229a-11e6-8f12-0e015c991c2d.png)

**Comment by geekwise-veronica-chavez** [comment]
done
