### ISSUE TITLE
responsive - courses - menu

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#17]
the hamburger icon doesn't show up and the sign up button doesn't exist

![their-course-menu](https://cloud.githubusercontent.com/assets/7436666/15559890/ed42694e-229a-11e6-9b43-0cc496cdf3f0.png)

![your-course-menu](https://cloud.githubusercontent.com/assets/7436666/15559891/ed439170-229a-11e6-8cc6-fb69100e6869.png)

**Comment by geekwise-veronica-chavez** [comment]
@Sramos9191 06/9/2016

**Comment by geekwise-veronica-chavez** [comment]
done
