### ISSUE TITLE
responsive - team - menu

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#18]
css styling is needed to mimic the look of menu in responsive mode

![their-menu](https://cloud.githubusercontent.com/assets/7436666/15560130/568b7a88-229d-11e6-8172-6afdd74f3529.png)

![your-menu](https://cloud.githubusercontent.com/assets/7436666/15560131/568d0c90-229d-11e6-932c-08877c0ae802.png)

**Comment by geekwise-veronica-chavez** [comment]
![image](https://cloud.githubusercontent.com/assets/17088567/15764415/9874ac6a-28df-11e6-8796-ae6771e771ea.png)

team header is white not red and my menu just meed to be centered

**Comment by Sramos9191** [comment]
@geekwise-veronica-chavez sounds good

**Comment by geekwise-veronica-chavez** [comment]
header fixed ... done

**Comment by geekwise-veronica-chavez** [comment]
this is done
