### ISSUE TITLE
responsive - cohort - cohort members

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#20]
the cohort members should all break into a column when it gets smaller

![their-cohorts](https://cloud.githubusercontent.com/assets/7436666/15560304/2e6b64f8-229f-11e6-95ce-39f40c14b29b.png)

![your-cohorts](https://cloud.githubusercontent.com/assets/7436666/15560305/2e6dbe9c-229f-11e6-8524-60dfb832bb8a.png)

**Comment by geekwise-veronica-chavez** [comment]
media query in cohort done
