### ISSUE TITLE
responsive - workshops - workshops

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#22]
the width should stretch across like theirs 

![their-workshop-workshops](https://cloud.githubusercontent.com/assets/7436666/15560350/90e7b6e0-229f-11e6-88c4-cad5f0126b50.png)
![your-workshop-workshops](https://cloud.githubusercontent.com/assets/7436666/15560349/90e40a86-229f-11e6-9e39-f34c814cd9ae.png)

**Comment by geekwise-veronica-chavez** [comment]
media query width set... content width 100%. done
