### ISSUE TITLE
responsive - workshops - menu

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#23]
the "about" link needs to stack with the rest of the navigational links

![their-menu](https://cloud.githubusercontent.com/assets/7436666/15560391/cacd98fc-229f-11e6-9ef2-7d8d9727feea.png)
![your-menu](https://cloud.githubusercontent.com/assets/7436666/15560392/cade46ca-229f-11e6-94f7-1674c15cc47a.png)

**Comment by geekwise-veronica-chavez** [comment]
![image](https://cloud.githubusercontent.com/assets/17088567/15764476/f65c7a7e-28df-11e6-9fa6-cceb9cc2f057.png)

will change the hamburgers background

**Comment by Sramos9191** [comment]
#28 is where we will continue with this @geekwise-veronica-chavez let me know when that's done 👍
