### ISSUE TITLE
responsive - sign up - course lists

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#24]
I like that you added the menu, can you fix the hamburger icon and stack "About" on top of the rest of the links

![your-menu](https://cloud.githubusercontent.com/assets/7436666/15560423/23a8bc04-22a0-11e6-88b8-b14054e37e2d.png)

**Comment by geekwise-veronica-chavez** [comment]
link for bootstrap is in it was missing

**Comment by Sramos9191** [comment]
#29  is where we will continue @geekwise-veronica-chavez
