### ISSUE TITLE
responsive - contact - body

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#25]
the background image shouldn't stretch it just needs to disappear as it gets smaller. 

![their-contact](https://cloud.githubusercontent.com/assets/7436666/15560435/4c53ed68-22a0-11e6-8813-b171336ee4d5.png)

![your-contact](https://cloud.githubusercontent.com/assets/7436666/15560441/59ce09f6-22a0-11e6-8117-db7a077a5ae7.png)

**Comment by geekwise-veronica-chavez** [comment]
background image set as cover... done
