### ISSUE TITLE
cohort - hamburger icon

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#26]
the hamburger icon is on the page without it being in responsive mode 

![screen shot 2016-06-02 at 4 25 10 pm](https://cloud.githubusercontent.com/assets/7436666/15764303/9eeb5a0e-28de-11e6-8168-8c89ca72a563.png)

**Comment by geekwise-veronica-chavez** [comment]
figured it out deleted wp css for img .... done

**Comment by Sramos9191** [comment]
perfect
