### ISSUE TITLE
sign up - hamburger icon - styling

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#29]
style hamburger icon to match the geekwise site 

![screen shot 2016-06-02 at 4 43 10 pm](https://cloud.githubusercontent.com/assets/7436666/15764631/4356e296-28e1-11e6-8821-2ebcae527f6d.png)

**Comment by geekwise-veronica-chavez** [comment]
hamburger fixed
