### ISSUE TITLE
About Us footer

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#3]
The footer needs to be bigger so that the text can fit inside of it.

how it appears on yours:
![screen shot 2016-05-17 at 2 29 25 pm](https://cloud.githubusercontent.com/assets/7436666/15339966/e5525100-1c3b-11e6-851e-1b5d91856a81.png)

how it should appear:
![screen shot 2016-05-17 at 2 29 57 pm](https://cloud.githubusercontent.com/assets/7436666/15339967/e5594316-1c3b-11e6-9d4e-896ae95a6849.png)

**Comment by geekwise-veronica-chavez** [comment]
done
