### ISSUE TITLE
workshop - remove page - #featured

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#30]
remove this page, as the Geekwise Academy site no longer has the page on their site

**Comment by geekwise-veronica-chavez** [comment]
lmao seriously ???

**Comment by Sramos9191** [comment]
yes - now you’ve completed 2 issues!

**Comment by geekwise-veronica-chavez** [comment]
page and linked removed... thanks for you QA
