### ISSUE TITLE
about - content

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#31]
adjust the spacing between the "What" and "Why" portion. please see below:

original website:
![screen shot 2016-06-13 at 9 44 38 am](https://cloud.githubusercontent.com/assets/7436666/16015636/8c8ca26c-314b-11e6-83c6-fd2bfe736ea0.png)

your website:
![screen shot 2016-06-13 at 9 44 48 am](https://cloud.githubusercontent.com/assets/7436666/16015637/8c90ba64-314b-11e6-9ca0-aa511e2a3558.png)

**Comment by geekwise-veronica-chavez** [comment]
done
