### ISSUE TITLE
Course page

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#4]
the text inside the yellow buttons, "6 Weeks", the days of the week and "$250" need to be bold.

how it appears:
![screen shot 2016-05-17 at 2 31 28 pm](https://cloud.githubusercontent.com/assets/7436666/15340073/6fe94878-1c3c-11e6-8cfa-fb5191f85cb2.png)

how yours appears:
![screen shot 2016-05-17 at 2 31 37 pm](https://cloud.githubusercontent.com/assets/7436666/15340075/6ff14438-1c3c-11e6-9126-11940a7fc292.png)

**Comment by geekwise-veronica-chavez** [comment]
they omitted two courses do i do the same?

**Comment by Sramos9191** [comment]
yes

**Comment by geekwise-veronica-chavez** [comment]
removed class and added stem

**Comment by geekwise-veronica-chavez** [comment]
removed class from site

**Comment by Sramos9191** [comment]
@geekwise-veronica-chavez please make the STEM button text bold. Style the table contents properly to match the one on the site: (ie: underline the topic, italicize the description, bold the first line for each column and update the content to match: http://geekwiseacademy.com/courses

**Comment by geekwise-veronica-chavez** [comment]
all updated course are in

**Comment by geekwise-veronica-chavez** [comment]
all courses are in
