### ISSUE TITLE
workshop missing stem program button

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#5]
under the header at the top of the page the "stem program" button is missing

![screen shot 2016-05-17 at 2 41 28 pm](https://cloud.githubusercontent.com/assets/7436666/15340293/85d84c50-1c3d-11e6-92ed-95aae7d85035.png)

**Comment by Sramos9191** [comment]
@geekwise-veronica-chavez please make the text bold

**Comment by geekwise-veronica-chavez** [comment]
05/25/2016
@Sramos9191

**Comment by geekwise-veronica-chavez** [comment]
stem bar is in and linked

**Comment by geekwise-veronica-chavez** [comment]
![image](https://cloud.githubusercontent.com/assets/17088567/15935977/26693002-2e1e-11e6-9937-5e49165d2790.png)

and no workshop page to update
