### ISSUE TITLE
home page bottom portion

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#6]
*The "Fast, No Fluff" text needs to be smaller.
*adjust the space between the "Fast, No Fluff" line 
*add more space between the bottom 3 columns

their site:
![screen shot 2016-05-20 at 8 59 23 am](https://cloud.githubusercontent.com/assets/7436666/15433997/bfe94920-1e69-11e6-9026-ce68b5b67c0c.png)

your site:
![screen shot 2016-05-20 at 8 59 40 am](https://cloud.githubusercontent.com/assets/7436666/15433996/bfdf04ba-1e69-11e6-968e-bce305bd8383.png)

**Comment by geekwise-veronica-chavez** [comment]
fixed the spacing and font -size

**Comment by Sramos9191** [comment]
@geekwise-veronica-chavez  the "we teach technology skills that you can use to make money" line should be bigger and bold, and less space between that line and the "Fast. No Fluff"

**Comment by geekwise-veronica-chavez** [comment]
5/25/2016
@Sramos9191

**Comment by geekwise-veronica-chavez** [comment]
spacing and font are done

**Comment by geekwise-veronica-chavez** [comment]
this issue is fixed

**Comment by Sramos9191** [comment]
what happened to the vertical lines?

![screen shot 2016-06-10 at 11 03 14 am](https://cloud.githubusercontent.com/assets/7436666/15973987/fd6f6bc0-2efa-11e6-9068-d25d5faa0a2a.png)

**Comment by geekwise-veronica-chavez** [comment]
there are in sorry

**Comment by geekwise-veronica-chavez** [comment]
that is another issue #12 which is now done

**Comment by Sramos9191** [comment]
got it.
