### ISSUE TITLE
About content issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#7]
@geekwise-veronica-chavez  please make the body text bold and underline "Length", "Time", "Location", and "Cost" - also change the location to the same one as the contact page.

**Comment by geekwise-veronica-chavez** [comment]
have trouble underlining those words they are in a loop, but ill try 06/3/2016

**Comment by geekwise-veronica-chavez** [comment]
done
