### ISSUE TITLE
team issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/geekwise-wordpress#9]
@geekwise-veronica-chavez  please adjust the body font type to match the site

**Comment by geekwise-veronica-chavez** [comment]
font is lato and its done

**Comment by Sramos9191** [comment]
@geekwise-veronica-chavez 
it looks like it's not getting used

![screen shot 2016-06-08 at 11 56 31 am](https://cloud.githubusercontent.com/assets/7436666/15907000/1ff180c0-2d70-11e6-9b7e-156029152ebd.png)

**Comment by geekwise-veronica-chavez** [comment]
[image: Inline image 1]
than something is wrong

**Comment by Sramos9191** [comment]
yes, there is an error somewhere within the css preventing the font from rendering as it should

**Comment by geekwise-veronica-chavez** [comment]
ok check it now
